#!/usr/bin/env python3
"""Tier 1 navigation extraction: mirror the source Docusaurus sidebar into docs.json.

The published sidebar lives at `versioned_sidebars/version-0.14-sidebars.json` in
reddit/devvit-docs. Its shape maps onto Mintlify almost one-to-one:

  html item with `sidebar-section-header`  ->  a top-level Mintlify group
                                               (non-collapsible on both sides)
  category                                 ->  nested group with expanded:false
                                               (the source renders a chevron and
                                               auto-collapses; autoCollapseCategories
                                               is false so visited sections stay open)
  doc / bare string                        ->  page slug, sidebarTitle from `label`
  link                                     ->  stub MDX with `url:` frontmatter
  autogenerated dirName                    ->  every page under that directory

Pages the source publishes but leaves out of its sidebar are collected into a
single trailing "API reference" group, or placed in the one existing nested group
that already covers their topic. Both cases are recorded in parity-manifest.json.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

SOURCE_BASE = "https://developers.reddit.com/docs"

DISCORD_URL = "https://developers.reddit.com/discord"
SUBREDDIT_URL = "https://www.reddit.com/r/Devvit"
FUNDS_CURRENT_URL = (
    "https://support.reddithelp.com/hc/en-us/articles/"
    "27958169342996-Reddit-Developer-Funds-2025-Terms"
)
FUNDS_2026_URL = (
    "https://support.reddithelp.com/hc/en-us/articles/"
    "50860336905108-Reddit-Developer-Funds-H2-2026-Terms"
)

# External sidebar rows the source renders as `type: "link"`. Mintlify needs a
# real page slug inside a group's `pages` array, so each one becomes a stub MDX
# with `url:` frontmatter (style-docs -> "External link in the sidebar").
LINK_STUBS = {
    FUNDS_2026_URL: ("resources/developer-funds-h2-2026", "Developer Funds - August 2026"),
    DISCORD_URL: ("resources/discord", "Discord"),
    SUBREDDIT_URL: ("resources/devvit-subreddit", "r/Devvit"),
}
# The source already publishes a page whose only job is to bounce to the current
# Developer Funds terms, so it doubles as that sidebar row instead of a new stub.
LINK_PAGES = {FUNDS_CURRENT_URL: ("earn-money/reddit_developer_funds", "Developer Funds - Current")}

# Source pages that are published but absent from the source sidebar, placed in
# the existing nested group that already covers their topic.
ORPHAN_PLACEMENTS = {
    "capabilities/interactive-posts/interactive_posts_overview": (
        ("Capabilities", "Post Creation & Navigation"), 0, "Overview"),
    "capabilities/server/splash-screen": (
        ("Capabilities", "Post Creation & Navigation", "Launch Screen"), 99, ""),
    "capabilities/server/launch_screen_and_entry_points/splash_migration": (
        ("Capabilities", "Post Creation & Navigation", "Launch Screen"), 99, ""),
}

# Source pages the source itself keeps out of navigation and out of its own
# search index. Mirrored with `hidden: true` so the URL stays live.
HIDDEN_PAGES = {
    "capabilities/server/http-fetch":
        "legacy fork of /capabilities/http-fetch; unlinked on the source and has "
        "no distinct sidebar label. Content preserved verbatim, URL stays live.",
    "examples/tutorials/mod-tool":
        "title-only stub on the source; unlinked from the sidebar and excluded "
        "from the source's own search index (ignoreFiles: three_strikes).",
}

# Legacy duplicate URLs: the source publishes two copies, one of which is stale.
DUPLICATE_REDIRECTS = {
    "earn-money/payments/analytics/journeys-dashboard": "capabilities/analytics/journeys-dashboard",
}

# The one "HTTP Fetch" row in the source sidebar becomes a small collapsible
# group so the published-but-unlinked policy page has a home next to it.
HTTP_FETCH_GROUP = {
    "group": "HTTP Fetch",
    "expanded": False,
    "pages": ["capabilities/http-fetch", "capabilities/server/http-fetch-policy"],
}

TRAILING_GROUP_LABEL = "Resources"

# Sidebar-label condensation, per style-docs. `title` (and therefore the page
# H1, browser tab, and search text) stays verbatim; only the ~240px sidebar
# label changes.
#
# - Group landing pages take "Overview" so the sidebar stops reading
#   "HTTP Fetch > HTTP Fetch" and "Launch Screen > View Modes, Launch Screens,
#   and Entry Points".
# - The three migration guides all carry the trailing product boilerplate
#   "to Devvit Web", which is already established by their group label.
SIDEBAR_LABEL_OVERRIDES = {
    "capabilities/http-fetch": "Overview",
    "capabilities/server/launch_screen_and_entry_points/launch_overview": "Overview",
    "guides/migrate/devvit-singleton": "Migrating Blocks/Mod Tools",
    "guides/migrate/devvit-web-experimental": "Migrating from Devvit Web Experimental",
    "guides/migrate/inline-web-view": "Migrating from useWebView",
}

BLOG_TAGS = [
    "bolt", "cabbage-systems", "cross-platform", "design", "devvit", "game",
    "hackathon", "hello", "honk", "mobile", "pixelary", "riddonkulous",
    "skyboard", "sword-and-supper",
]


def load_sidebar(src_repo: Path, version: str) -> list:
    path = src_repo / "versioned_sidebars" / f"version-{version}-sidebars.json"
    return json.loads(path.read_text(encoding="utf-8"))["tutorialSidebar"]


def sidebar_labels(src_repo: Path, version: str) -> dict[str, str]:
    """doc id -> the short label the source sidebar shows for it."""
    labels: dict[str, str] = {}

    def walk(items: list) -> None:
        for item in items:
            if isinstance(item, str):
                continue
            if item.get("type") == "doc" and item.get("label"):
                labels[item["id"]] = item["label"]
            elif item.get("type") == "category":
                walk(item["items"])

    walk(load_sidebar(src_repo, version))
    for url, (doc_id, label) in LINK_PAGES.items():
        labels[doc_id] = label
    for doc_id, (_, _, label) in ORPHAN_PLACEMENTS.items():
        if label:
            labels[doc_id] = label
    labels.update(SIDEBAR_LABEL_OVERRIDES)
    return labels


# ---------------------------------------------------------------------------
# Sidebar -> Mintlify groups
# ---------------------------------------------------------------------------

def _section_header(item: dict) -> str | None:
    if item.get("type") != "html":
        return None
    if "sidebar-section-header" not in (item.get("className") or ""):
        return None
    m = re.search(r">([^<]+)<", item.get("value", ""))
    return m.group(1).strip() if m else None


def _expand_autogenerated(dir_name: str, all_paths: set[str]) -> list[str]:
    prefix = dir_name.rstrip("/") + "/"
    return sorted(p for p in all_paths if p.startswith(prefix))


def _convert_items(items: list, id_to_path: dict[str, str], all_paths: set[str],
                   used: set[str]) -> list:
    out: list = []
    for item in items:
        if isinstance(item, str):
            path = id_to_path.get(item, item)
            out.append(path)
            used.add(path)
        elif item.get("type") == "doc":
            url_page = LINK_PAGES.get(item.get("href", ""))
            path = id_to_path.get(item["id"], item["id"])
            out.append(path)
            used.add(path)
        elif item.get("type") == "link":
            href = item["href"]
            if href in LINK_PAGES:
                path = id_to_path.get(LINK_PAGES[href][0], LINK_PAGES[href][0])
            else:
                path = LINK_STUBS[href][0]
            out.append(path)
            used.add(path)
        elif item.get("type") == "category":
            group = {"group": item["label"], "expanded": False, "pages": []}
            for child in item["items"]:
                if isinstance(child, dict) and child.get("type") == "autogenerated":
                    for path in _expand_autogenerated(child["dirName"], all_paths):
                        group["pages"].append(path)
                        used.add(path)
                else:
                    group["pages"].extend(
                        _convert_items([child], id_to_path, all_paths, used))
            out.append(group)
        elif item.get("type") == "autogenerated":
            for path in _expand_autogenerated(item["dirName"], all_paths):
                out.append(path)
                used.add(path)
    return out


def _inject_orphans(groups: list, id_to_path: dict[str, str], used: set[str]) -> None:
    """Place published-but-unlinked pages into the nested group that fits them."""
    def find(container: list, label: str):
        for entry in container:
            if isinstance(entry, dict) and entry.get("group") == label:
                return entry
        return None

    for doc_id, (trail, index, _label) in ORPHAN_PLACEMENTS.items():
        path = id_to_path[doc_id]
        node = find(groups, trail[0])
        for label in trail[1:]:
            node = find(node["pages"], label)
        pages = node["pages"]
        pages.insert(min(index, len(pages)), path)
        used.add(path)

    # Swap the flat "HTTP Fetch" row for the small collapsible group.
    capabilities = find(groups, "Capabilities")
    pages = capabilities["pages"]
    idx = pages.index("capabilities/http-fetch")
    pages[idx] = HTTP_FETCH_GROUP
    used.update(HTTP_FETCH_GROUP["pages"])


# ---------------------------------------------------------------------------
# Generated API reference
# ---------------------------------------------------------------------------

KIND_LABELS = {
    "classes": "Classes",
    "interfaces": "Interfaces",
    "enumerations": "Enumerations",
    "functions": "Functions",
    "variables": "Variables",
    "type-aliases": "Type aliases",
}
KIND_ORDER = ["classes", "interfaces", "enumerations", "functions", "variables", "type-aliases"]


def _alpha_buckets(paths: list[str], target: int = 45) -> list:
    """Split a long alphabetical run into contiguous A–C / D–G style subgroups."""
    if len(paths) <= target * 1.4:
        return paths
    letters: dict[str, list[str]] = {}
    for path in paths:
        letters.setdefault(path.rsplit("/", 1)[-1][0].upper(), []).append(path)
    buckets: list[tuple[list[str], list[str]]] = []
    current_keys: list[str] = []
    current: list[str] = []
    for key in sorted(letters):
        current_keys.append(key)
        current.extend(letters[key])
        if len(current) >= target:
            buckets.append((current_keys, current))
            current_keys, current = [], []
    if current:
        if buckets and len(current) < target / 3:
            buckets[-1][0].extend(current_keys)
            buckets[-1][1].extend(current)
        else:
            buckets.append((current_keys, current))
    out = []
    for keys, items in buckets:
        label = keys[0] if len(keys) == 1 else f"{keys[0]}–{keys[-1]}"
        out.append({"group": label, "expanded": False, "pages": sorted(items)})
    return out


def _package_group(label: str, root: str, remaining: set[str]) -> dict | None:
    scoped = sorted(p for p in remaining if p == root or p.startswith(root + "/"))
    if not scoped:
        return None
    pages: list = []
    if root in scoped:
        pages.append(root)
        scoped.remove(root)

    def take(prefix: str) -> list[str]:
        hit = [p for p in scoped if p.startswith(prefix)]
        for p in hit:
            scoped.remove(p)
        return sorted(hit)

    namespaces = sorted({
        p.split("/namespaces/")[1].split("/")[0]
        for p in scoped if "/namespaces/" in p
    })

    for kind in KIND_ORDER:
        hit = take(f"{root}/{kind}/")
        if hit:
            pages.append({
                "group": KIND_LABELS[kind],
                "expanded": False,
                "pages": _alpha_buckets(hit),
            })

    for namespace in namespaces:
        ns_root = f"{root}/@devvit/namespaces/{namespace}"
        ns_pages: list = []
        if ns_root in scoped:
            scoped.remove(ns_root)
            ns_pages.append(ns_root)
        for kind in KIND_ORDER:
            hit = take(f"{ns_root}/{kind}/")
            if hit:
                ns_pages.append({
                    "group": KIND_LABELS[kind],
                    "expanded": False,
                    "pages": _alpha_buckets(hit),
                })
        pages.append({"group": f"{namespace} namespace", "expanded": False, "pages": ns_pages})

    for sub in sorted({p.split("/")[len(root.split("/"))] for p in scoped}):
        sub_root = f"{root}/{sub}"
        sub_pages: list = []
        if sub_root in scoped:
            scoped.remove(sub_root)
            sub_pages.append(sub_root)
        for kind in KIND_ORDER:
            hit = take(f"{sub_root}/{kind}/")
            if hit:
                sub_pages.append({
                    "group": KIND_LABELS[kind],
                    "expanded": False,
                    "pages": _alpha_buckets(hit),
                })
        rest = take(f"{sub_root}/")
        sub_pages.extend(rest)
        if sub_pages:
            pages.append({
                "group": sub.replace("-", " ").replace("RedditClient", "RedditClient"),
                "expanded": False,
                "pages": sub_pages,
            })

    pages.extend(sorted(scoped))
    remaining.difference_update(
        {p for p in list(remaining) if p == root or p.startswith(root + "/")})
    return {"group": label, "expanded": False, "pages": pages}


# ---------------------------------------------------------------------------
# Stub pages
# ---------------------------------------------------------------------------

def build_stubs(repo: Path) -> list[dict]:
    rows: list[dict] = []
    for url, (path, label) in LINK_STUBS.items():
        dest = repo / f"{path}.mdx"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(
            "---\n"
            f'title: "{label}"\n'
            f'url: "{url}"\n'
            "---\n\n"
            f"This sidebar entry links out to [{label}]({url}), matching the "
            "same entry on the source sidebar.\n",
            encoding="utf-8",
        )
        rows.append({
            "source_url": url,
            "source_title": label,
            "source_sidebar_label": label,
            "source_h1": "",
            "source_description": "",
            "normalized_path": f"/{path}",
            "nav_section": "",
            "converted_file": f"{path}.mdx",
            "status": "done",
            "notes": "external sidebar row from the source sidebar, reproduced "
                     "with url: frontmatter",
        })
    return rows


# ---------------------------------------------------------------------------
# Redirects + docs.json
# ---------------------------------------------------------------------------

def build_redirects(blog_anchors: dict[str, str]) -> list[dict]:
    redirects: list[dict] = [
        {"source": "/docs", "destination": "/introduction/introduction"},
        {"source": "/docs/introduction/introduction", "destination": "/introduction/introduction"},
        # The Ads API root page used to live at /ads-api/overview, before the
        # landing page replica took over the product root.
        {"source": "/ads-api/overview", "destination": "/ads-api"},
    ]
    for slug, anchor in sorted(blog_anchors.items()):
        target = f"/blog#{anchor}"
        redirects.append({"source": f"/blog/{slug}", "destination": target})
        redirects.append({"source": f"/docs/blog/{slug}", "destination": target})
    for extra in ("archive", "tags"):
        redirects.append({"source": f"/blog/{extra}", "destination": "/blog"})
        redirects.append({"source": f"/docs/blog/{extra}", "destination": "/blog"})
    for tag in BLOG_TAGS:
        redirects.append({"source": f"/blog/tags/{tag}", "destination": "/blog"})
        redirects.append({"source": f"/docs/blog/tags/{tag}", "destination": "/blog"})
    for legacy, canonical in DUPLICATE_REDIRECTS.items():
        redirects.append({"source": f"/{legacy}", "destination": f"/{canonical}"})
    # Catch-all for the source's /docs/* URL space, last so the explicit rules win.
    redirects.append({"source": "/docs/:slug*", "destination": "/:slug*"})
    return redirects


def build(repo: Path, src_repo: Path, version: str, id_to_path: dict[str, str],
          titles: dict[str, str], blog_anchors: dict[str, str]
          ) -> tuple[dict, list[dict], dict[str, str]]:
    all_paths = set(id_to_path.values())
    used: set[str] = set()
    sidebar = load_sidebar(src_repo, version)

    groups: list[dict] = []
    current: dict | None = None
    for item in sidebar:
        header = _section_header(item)
        if header:
            current = {"group": header, "pages": []}
            groups.append(current)
            continue
        if isinstance(item, dict) and item.get("type") == "html":
            continue  # `<hr/>` dividers: Mintlify separates top-level groups already
        if current is None:
            current = {"group": TRAILING_GROUP_LABEL, "pages": []}
            groups.append(current)
        converted = _convert_items([item], id_to_path, all_paths, used)
        current["pages"].extend(converted)

    # Everything after the last `<hr/>` in the source has no section header of
    # its own; Mintlify top-level groups require a label.
    tail_start = None
    for index, item in enumerate(sidebar):
        if _section_header(item):
            tail_start = index
    tail_items = []
    seen_divider = False
    for item in sidebar[tail_start:]:
        if isinstance(item, dict) and "sidebar-divider" in (item.get("className") or ""):
            seen_divider = True
            continue
        if seen_divider:
            tail_items.append(item)
    if tail_items:
        tail_paths = _convert_items(tail_items, id_to_path, all_paths, set())
        for entry in tail_paths:
            if entry in groups[-1]["pages"]:
                groups[-1]["pages"].remove(entry)
        groups.append({"group": TRAILING_GROUP_LABEL, "pages": ["blog"] + tail_paths})
        used.add("blog")

    _inject_orphans(groups, id_to_path, used)

    for doc_id in HIDDEN_PAGES:
        used.add(id_to_path[doc_id])
    for doc_id in DUPLICATE_REDIRECTS:
        used.add(id_to_path[doc_id])
    used.add("index")
    used.add("changelog")

    remaining = {p for p in all_paths if p not in used}
    api_pages: list = []
    for label, root in (("@devvit/public-api", "api/public-api"),
                        ("@devvit/reddit", "api/redditapi")):
        group = _package_group(label, root, remaining)
        if group:
            api_pages.append(group)
    leftover = sorted(remaining)
    if leftover:
        raise SystemExit(f"pages not placed in navigation: {leftover[:20]}")
    groups.append({
        "group": "API reference",
        "pages": [API_PLAYGROUND_GROUP] + api_pages,
    })

    # The version dropdown hangs off each product rather than off `navigation`.
    # A product-level list is merged into a site-level one instead of replacing
    # it, which would show Devvit's SDK versions in the Ads API dropdown.
    nav = {
        "products": [
            {"product": "Developer Platform", "icon": "code", "groups": groups,
             "global": {"versions": GLOBAL_VERSIONS}},
            {"product": "Ads API", "icon": "bullhorn", "tabs": ADS_API_TABS,
             "global": {"versions": ADS_API_VERSIONS}},
        ],
    }

    sections: dict[str, str] = {}

    def walk(entries: list, trail: list[str]) -> None:
        for entry in entries:
            if isinstance(entry, str):
                sections["/" + entry] = " > ".join(trail)
            else:
                walk(entry["pages"], trail + [entry["group"]])

    walk(groups, [])
    for doc_id, reason in HIDDEN_PAGES.items():
        sections["/" + id_to_path[doc_id]] = "(hidden — matches source)"
    for doc_id, canonical in DUPLICATE_REDIRECTS.items():
        sections["/" + id_to_path[doc_id]] = "(redirect to /" + canonical + ")"

    return nav, build_redirects(blog_anchors), sections


def excluded_rows(urls: list[str], manifest: list[dict]) -> list[dict]:
    """Sitemap URLs that are source chrome rather than content pages."""
    covered = {row["source_url"].rstrip("/") for row in manifest}
    reasons = {
        f"{SOURCE_BASE}/search":
            "Docusaurus search UI route, not a content page; Mintlify ships its "
            "own search and AI assistant.",
        f"{SOURCE_BASE}/0.13":
            "older documentation version root. The source marks 0.11-0.13 and "
            "next as noIndex and filters them out of its own sitemap; only the "
            "published 0.14 version is in scope.",
        f"{SOURCE_BASE}/blog":
            "blog index route, replaced by the consolidated /blog Update timeline.",
        f"{SOURCE_BASE}/blog/archive":
            "generated blog archive route, replaced by the consolidated /blog "
            "Update timeline.",
        f"{SOURCE_BASE}/blog/tags":
            "generated tag index route; the consolidated /blog timeline carries "
            "the same tags as Mintlify Update tag filters.",
    }
    rows: list[dict] = []
    for url in urls:
        key = url.rstrip("/")
        if key in covered:
            continue
        reason = reasons.get(key)
        if reason is None and "/blog/tags/" in url:
            reason = (
                "generated tag listing route; the tag is preserved on the "
                "consolidated /blog Update timeline and the URL redirects there.")
        if reason is None:
            continue
        status = "done" if "/blog" in url else "excluded"
        rows.append({
            "source_url": url,
            "source_title": "",
            "source_sidebar_label": "",
            "source_h1": "",
            "source_description": "",
            "normalized_path": "/blog" if "/blog" in url else "",
            "nav_section": "Resources" if "/blog" in url else "",
            "converted_file": "blog.mdx" if "/blog" in url else "",
            "status": status,
            "notes": reason,
        })
    return rows


DOCS_JSON_HEAD = {
    "$schema": "https://mintlify.com/docs.json",
    "theme": "luma",
    "name": "Reddit for Developers",
    "description": "Build powerful apps and immersive experiences to enhance the communities you love.",
    "colors": {"primary": "#FF4500", "light": "#FE7C53", "dark": "#D93A00"},
    "appearance": {"default": "system"},
    # Pixel-sampled from the live source at 1440px: the page canvas is #FFFFFF
    # in light mode and #0B1416 in dark mode. The navbar and footer sit on
    # slightly lighter dark tones; those are in custom.css because docs.json
    # `background` only sets one tone. No `decoration` — the source is flat.
    "background": {"color": {"light": "#FFFFFF", "dark": "#0B1416"}},
    # The source serves one logo for both color modes: the wordmark is Reddit
    # orangered (#FF4500), which holds contrast on white and on #0B1416.
    "logo": {
        "light": "/images/brand/logo.svg",
        "dark": "/images/brand/logo.svg",
        "href": "https://developers.reddit.com/",
    },
    "favicon": "/images/brand/devvit-icon.png",
}

# The source docs navbar carries a version dropdown (Next / 0.14 / 0.13 / 0.12
# / 0.11) next to the logo. `navigation.global.versions` is Mintlify's
# equivalent and renders in the same place. Only 0.14 -- the version the source
# publishes by default and the one this preview mirrors -- exists locally; the
# other entries point at the versions the source still hosts, so the switcher
# behaves the same way it does on the source site.
GLOBAL_VERSIONS = [
    {"version": "Next", "href": "https://developers.reddit.com/docs/next"},
    {"version": "0.14", "href": "/introduction/introduction", "default": True},
    {"version": "0.13", "href": "https://developers.reddit.com/docs/0.13"},
    {"version": "0.12", "href": "https://developers.reddit.com/docs/0.12"},
    {"version": "0.11", "href": "https://developers.reddit.com/docs/0.11"},
]

# The Ads API navbar carries its own version dropdown (v3 / v2 (Deprecated)),
# so the Ads API product overrides GLOBAL_VERSIONS rather than showing Devvit's
# SDK versions on advertising pages. Only v3 was migrated; v2 is deprecated and
# stays on the source site.
ADS_API_VERSIONS = [
    {"version": "v3", "href": "/ads-api/api/introduction", "default": True},
    {"version": "v2 (Deprecated)",
     "href": "https://ads-api.reddit.com/docs/v2/api/reddit-advertising-api"},
]

# Devvit's own HTTP contract, documented across capabilities/server/* and
# capabilities/client/*. These are the only HTTP endpoints in the corpus: the
# rest of the API reference is a TypeScript SDK with no endpoints to call.
# Callback/managed-token external endpoints have a documented public base URL,
# so those get the interactive playground; the platform-invoked /internal and
# app-internal /api routes are documented with a copyable endpoint instead.
API_PLAYGROUND_GROUP = {
    "group": "API playground",
    "expanded": False,
    "pages": [
        "api-playground/overview",
        "api-playground/external-endpoint",
        "api-playground/menu-action",
        "api-playground/trigger-event",
        "api-playground/scheduled-task",
        "api-playground/form-submit",
        "api-playground/app-endpoint",
    ],
}

# Second preview: ads-api.reddit.com/docs. A different product for a different
# audience (advertisers rather than app developers), so it gets its own entry in
# the product switcher rather than being mixed into the Devvit sidebar.
# The endpoint pages are generated by Mintlify from the reconstructed OpenAPI
# document, which is why the reference group carries `openapi` and no pages.
ADS_API_GROUPS = [
    {
        "group": "Get started",
        "pages": [
            "ads-api/guides/quick-start",
            "ads-api/guides/quick-start/create-dev-app",
            "ads-api/guides/quick-start/authenticate",
            "ads-api/guides/quick-start/rate-limiting",
        ],
    },
    {
        "group": "Guides",
        "pages": [
            {
                "group": "Campaign Management",
                "expanded": False,
                "pages": [
                    "ads-api/guides/programs/campaign",
                    "ads-api/guides/programs/campaign/campaign-setup",
                    "ads-api/guides/programs/campaign/max-campaign-setup",
                    "ads-api/guides/programs/campaign/campaign-objective-migration",
                    "ads-api/guides/programs/campaign/match-destination-and-click-url",
                    "ads-api/guides/programs/campaign/preview-an-ad",
                ],
            },
            {
                "group": "Conversions API",
                "expanded": False,
                "pages": [
                    "ads-api/guides/programs/capi",
                    "ads-api/guides/programs/capi/direct-integration",
                    "ads-api/guides/programs/capi/best-practices",
                    "ads-api/guides/programs/capi/click-id-persistence",
                    "ads-api/guides/programs/capi/verify-events",
                    "ads-api/guides/programs/capi/error-handling",
                    "ads-api/guides/programs/capi/migration",
                ],
            },
            {
                "group": "Reporting",
                "expanded": False,
                "pages": [
                    "ads-api/guides/programs/reporting",
                    "ads-api/guides/programs/reporting/filter-metrics",
                    "ads-api/guides/programs/reporting/add-adaptive-time",
                    "ads-api/guides/programs/reporting/get-custom-event-report",
                    "ads-api/guides/programs/reporting/upcoming-reporting-api-changes",
                ],
            },
            {
                "group": "Data Deletion",
                "expanded": False,
                "pages": [
                    "ads-api/guides/programs/data-deletion",
                    "ads-api/guides/programs/data-deletion/delete-user-data",
                ],
            },
            {
                "group": "Product Catalogs",
                "expanded": False,
                "pages": [
                    "ads-api/guides/programs/product-catalogs",
                    "ads-api/guides/programs/product-catalogs/catalog-setup",
                    "ads-api/guides/programs/product-catalogs/filter-products",
                ],
            },
            {
                "group": "Targeting",
                "expanded": False,
                "pages": [
                    "ads-api/guides/programs/targeting",
                    "ads-api/guides/programs/targeting/manage-customer-lists",
                ],
            },
            {
                "group": "Business Management",
                "expanded": False,
                "pages": [
                    "ads-api/guides/programs/business",
                    "ads-api/guides/programs/business/fetch-accounts",
                    "ads-api/guides/programs/business/system-users",
                ],
            },
        ],
    },
    # The source's API section opens with the Introduction page and then lists
    # one group per tag. Mintlify keeps generating every tag group from the
    # OpenAPI document even when `pages` names an extra ordinary page, so the
    # two can live in one group exactly as the source has them.
    {
        "group": "API",
        # `directory` keeps the generated endpoint pages inside the Ads API
        # product's own path instead of Mintlify's default /api-reference,
        # which would sit oddly next to the Devvit docs' own /api pages.
        "openapi": {
            "source": "openapi/reddit-ads-api-v3.json",
            "directory": "ads-api/reference",
        },
        "pages": ["ads-api/api/introduction"],
    },
]

# The source runs four sections across its navbar -- Guides, API, What's New
# and Blog -- and keeps them there on every docs page. Tabs are Mintlify's
# equivalent: they render as a row in the navbar and each carries its own
# sidebar. API leads so that picking "Ads API" in the product switcher lands on
# the API reference introduction rather than on the marketing landing page,
# which is the product's first page in navigation order.
ADS_API_TABS = [
    {"tab": "API", "groups": [g for g in ADS_API_GROUPS if g["group"] == "API"]},
    {"tab": "Guides", "groups": [g for g in ADS_API_GROUPS if g["group"] != "API"]},
    {"tab": "What's New", "pages": ["ads-api/whats-new"]},
    {"tab": "Blog", "pages": ["ads-api/blog"]},
]

DOCS_JSON_TAIL = {
    "api": {
        "playground": {"display": "interactive", "proxy": False},
        "mdx": {
            # Documented in capabilities/server/external-endpoints: an app's
            # external endpoints are reachable at this host, authenticated with
            # an `externalToken` query parameter.
            "server": "https://{appSlug}-{subredditId}-external.devvit.net",
            "auth": {"method": "key", "name": "externalToken"},
        },
        "examples": {
            "languages": ["curl", "typescript", "python"],
            "defaults": "required",
        },
    },
    "footer": {
        "links": [
            {
                "items": [
                    {"label": "Blog", "href": "/blog"},
                    {"label": "The Reddit Developer Fund", "href": FUNDS_CURRENT_URL},
                    {"label": "r/Devvit", "href": "https://www.reddit.com/r/devvit"},
                    {"label": "r/GamesOnReddit", "href": "https://www.reddit.com/r/GamesOnReddit"},
                    {"label": "Join our Discord", "href": DISCORD_URL},
                ]
            }
        ]
    },
    "contextual": {
        "options": [
            "copy", "view", "assistant", "chatgpt", "claude", "perplexity",
            "grok", "aistudio", "devin", "windsurf", "mcp", "add-mcp", "cursor",
            "vscode", "devin-mcp",
        ]
    },
    # Mandatory for previews. Nothing else belongs here: a site-wide og:title or
    # description in `metatags` overrides the per-page values on every page and
    # flattens the browser tab to the site name.
    "seo": {"metatags": {"robots": "noindex"}},
}


def write_docs_json(repo: Path, nav: dict, redirects: list[dict]) -> None:
    config = dict(DOCS_JSON_HEAD)
    config["navigation"] = nav
    config.update(DOCS_JSON_TAIL)
    config["redirects"] = redirects
    (repo / "docs.json").write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
